name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4

      - uses: kojoru/prepare-pipenv@v1
        with:
          python-version: ${{ matrix.python-version }}

      - run: pipenv install --dev

      - run: pipenv install -e .

      - run: pipenv run pytest

  publish:
    needs: build
    runs-on: ubuntu-latest

    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v4

      - uses: kojoru/prepare-pipenv@v1

      - run: pipenv install build
      - run: pipenv run python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}